---
swagger: '2.0'
info:
  description: UH-IaaS instance report API
  version: "1.0.0"
  title: UH-IaaS instance report API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

definitions:
  instance:
    type: object
    properties:
      ip:
        type: string
        description: 'private or public IPv4 address'
      name:
        type: string
        description: 'instance hostname'
      uptime:
        type: integer
        minimum: 0
        description: 'uptime in days'
    required:
      - name
      - ip
      - uptime
    example:
      name:    'demo-instance-01'
      ip:      '127.0.0.1'
      uptime:  10

paths:
  /v1/instance:
    get:
      operationId:  "report-api.instance.list_instances"
      tags:
        - Instance
      summary:      "Get instance report"
      description:  "Get the list of instances"
      responses:
        200:
          description: "Successful read instance list operation"
          schema:
            type: "array"
            items:
              properties:
                name:
                  type: "string"
                ip:
                  type: "string"
    post:
      operationId: report-api.instance.add_instance_report
      tags:
        - Instance
      summary: Add a new instance report
      description: This will add a new instance report
      parameters:
        - name: instance
          in: body
          description: Instance report to add
          required: True
          schema:
            $ref:  "#/definitions/instance"
      responses:
        201:
          description: Successful added instance report
