---
swagger: '2.0'
info:
  description: UH-IaaS instance report API
  version: "1.0.0"
  title: UH-IaaS instance report API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

definitions:
  instance:
    type: object
    properties:
      ip:
        type: string
        description: 'private or public IPv4 address'
      name:
        type: string
        description: 'instance hostname'
      uptime:
        type: integer
        minimum: 0
        description: 'uptime in days'
      updates:
        type: integer
        minimum: 0
        description: 'available security updates'
      kernel:
        type: string
        description: 'kernel version'
    required:
      - name
      - ip
      - uptime
      - updates
    example:
      name:    'demo-instance-01'
      ip:      '127.0.0.1'
      uptime:  10
      updates: 2

paths:
  /v1/instance:
    get:
      operationId:  "api.instance.list_instances"
      tags:
        - Instance
      summary:      "Get instance report"
      description:  "Get the list of instances"
      responses:
        200:
          description: "Successful read instance list operation"
          schema:
            $ref:  "#/definitions/instance"
      security:
        # enable authentication and require the "uid" scope for this endpoint
        - oauth2: ['admin']
    post:
      operationId: api.instance.add_instance_report
      tags:
        - Instance
      summary: Add a new instance report
      description: This will add a new instance report
      parameters:
        - name: instance
          in: body
          description: Instance report to add
          required: True
          schema:
            $ref:  "#/definitions/instance"
      responses:
        201:
          description: Successful added instance report

securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: /oauth2/dialog
    # you can also pass it as an environment variable TOKENINFO_URL
    #x-tokenInfoUrl: http://172.31.0.1:8080/oauth2/tokeninfo
    scopes:
      admin: Admin access to the service
      read: Read access to the service
